### ISSUE TITLE
No longer places districts or wonders

### ISSUE THREAD

**Issue by drelyea3** [kblease/ProductionQueue#38]
After the Summer 2017 Update, districts and wonders can no longer be placed.

**Comment by kblease** [comment]
Thanks for reporting this. Since this is really major, I'll try to get this fixed this weekend.

**Comment by jmalley** [comment]
If it helps, this is what I see in the lua log. The 'place wonder' confirmation box doesn't come up so I'm assuming this is related.

`Runtime Error: C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization VI\Base\Assets\UI\Popups\PopupDialog.lua:301: attempt to index a nil value
stack traceback:
	C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization VI\Base\Assets\UI\Popups\PopupDialog.lua:301: in function 'PopupDialog:IsOpen'
	C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization VI\Base\Assets\UI\Popups\PopupDialog.lua:240: in function 'PopupDialog:SetSize'
	C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization VI\Base\Assets\UI\Popups\PopupDialog.lua:73: in function 'PopupDialog:new'
	C:\Users\james\Documents\My Games\Sid Meier's Civilization VI\Mods\ProductionQueue\UI\StrategicView_MapPlacement.lua:54: in function 'ConfirmPlaceWonder'
	C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization VI\Base\Assets\UI\WorldInput.lua:1398: in function 'OnMouseBuildingPlacementEnd'
	C:\Program Files (x86)\Steam\steamapps\common\Sid Meier's Civilization VI\Base\Assets\UI\WorldInput.lua:3182: in function 'OnInputHandler'`

**Comment by heby1** [comment]
+1

**Comment by kblease** [comment]
This should be fixed now. Thanks for your patience!

**Comment by MrChrisRodriguez** [comment]
Howdy - this is still an issue. I'm getting the same error message as above. 

I did some investigating and the check you're using to determine if the usr has the late summer patch isn't working. It appears that some of us are getting 1.0.0.167 which [seems to correspond to 153264](https://cl.ly/3F1P2L3t3T3H) (which is smaller than 296277 you included in the patch). 

When I remove that check altogether (since I know I have the patch) it works. 

> Lua callstack:
WorldInput: yes
Runtime Error: C:\Emu\AppAssets\Base\Assets\UI\Popups\PopupDialog.lua:301: attempt to index a nil value
stack traceback:
	C:\Emu\AppAssets\Base\Assets\UI\Popups\PopupDialog.lua:301: in function 'PopupDialog:IsOpen'
	C:\Emu\AppAssets\Base\Assets\UI\Popups\PopupDialog.lua:240: in function 'PopupDialog:SetSize'
	C:\Emu\AppAssets\Base\Assets\UI\Popups\PopupDialog.lua:73: in function 'PopupDialog:new'
	C:\Emu\AppDataParent\Sid Meier's Civilization VI\Mods\ProductionQueue\UI\StrategicView_MapPlacement.lua:228: in function 'ConfirmPlaceDistrict'
	C:\Emu\AppAssets\Base\Assets\UI\WorldInput.lua:1426: in function 'OnMouseDistrictPlacementEnd'
	C:\Emu\AppAssets\Base\Assets\UI\WorldInput.lua:3182: in function 'OnInputHandler'

**Comment by kblease** [comment]
Hey @MrChrisRodriguez thanks for investigating. I figured that it was a long shot to rely on that for the long-term, but it was a nice band-aid for the past month. Since it appears all operating systems are now capable of running the Summer 2017 update, I have just gone ahead and removed the check.

Thanks again! Saved me some testing!
